// FCI breed groups — group number → name + full breed list
// Used by the scraper (to expand group authorizations) and the app (for display).
// Breed names are in Title Case to match FCI scraper output.

export const FCI_GROUP_NAMES = {
  1:  "Sheepdogs and Cattle Dogs",
  2:  "Pinscher, Schnauzer, Molossoid and Swiss Mountain Dogs",
  3:  "Terriers",
  4:  "Dachshunds",
  5:  "Spitz and Primitive Types",
  6:  "Scent Hounds and Related Breeds",
  7:  "Pointing Dogs",
  8:  "Retrievers, Flushing Dogs and Water Dogs",
  9:  "Companion and Toy Dogs",
  10: "Sighthounds",
};

export const FCI_GROUP_BREEDS = {
  1: [
    "Australian Cattle Dog","Australian Kelpie","Australian Shepherd","Barbado Da Terceira",
    "Bearded Collie","Beauceron","Belgian Shepherd Dog","Bergamasco Sheepdog","Berger Picard",
    "Border Collie","Bouvier Des Ardennes","Bouvier Des Flandres","Briard",
    "Carpathian Shepherd Dog","Catalan Sheepdog","Croatian Sheepdog","Dutch Shepherd Dog",
    "German Shepherd Dog","Hollandse Herder","Karst Shepherd Dog","Komondor","Kuvasz",
    "Lancashire Heeler","Lupino Del Gigante","Maremma and Abruzzese Sheepdog","Mudi",
    "Old English Sheepdog","Polish Lowland Sheepdog","Polish Tatra Sheepdog","Puli","Pumi",
    "Pyrenean Sheepdog","Rough Collie","Saarloos Wolfdog","Sarplaninac","Schapendoes",
    "Shetland Sheepdog","Smooth Collie","South Russian Ovtcharka","Tornjak",
    "White Swiss Shepherd Dog",
  ],
  2: [
    "Affenpinscher","Appenzeller Sennenhund","Bernese Mountain Dog","Boxer","Broholmer",
    "Bullmastiff","Ca De Bou","Cane Corso Italiano","Cao De Castro Laboreiro",
    "Cimarrón Uruguayo","Dobermann","Dogue De Bordeaux","Entlebucher Mountain Dog",
    "Estrela Mountain Dog","Fila Brasileiro","German Pinscher","Giant Schnauzer",
    "Great Dane","Greater Swiss Mountain Dog","Hovawart","Landseer","Leonberger",
    "Mastin Espanol","Mastin Del Pirineo","Mastiff","Miniature Pinscher","Miniature Schnauzer",
    "Neapolitan Mastiff","Newfoundland","Rottweiler","Saint Bernard","Standard Schnauzer",
    "Tibetan Mastiff","Tosa",
  ],
  3: [
    "Airedale Terrier","Australian Terrier","Bedlington Terrier","Border Terrier",
    "Bull Terrier","Bull Terrier Miniature","Cairn Terrier","Cesky Terrier",
    "Dandie Dinmont Terrier","Fox Terrier (Smooth)","Fox Terrier (Wire)",
    "Glen Of Imaal Terrier","Irish Glen Of Imaal Terrier","Irish Soft Coated Wheaten Terrier",
    "Irish Terrier","Jack Russell Terrier","Kerry Blue Terrier","Lakeland Terrier",
    "Manchester Terrier","Norfolk Terrier","Norwich Terrier","Parson Russell Terrier",
    "Scottish Terrier","Sealyham Terrier","Skye Terrier","Welsh Terrier",
    "West Highland White Terrier","Yorkshire Terrier",
  ],
  4: [
    "Dachshund","Dachshund (Miniature Long-haired)","Dachshund (Miniature Smooth-haired)",
    "Dachshund (Miniature Wire-haired)","Dachshund (Rabbit Long-haired)",
    "Dachshund (Rabbit Smooth-haired)","Dachshund (Rabbit Wire-haired)",
    "Dachshund (Standard Long-haired)","Dachshund (Standard Smooth-haired)",
    "Dachshund (Standard Wire-haired)",
  ],
  5: [
    "Akita","Alaskan Malamute","American Akita","Basenji","Canaan Dog","Chow Chow",
    "Cirneco Dell'Etna","Eurasier","Finnish Lapphund","Finnish Spitz",
    "German Spitz (Giant)","German Spitz (Medium)","German Spitz (Small)","German Spitz (Toy)",
    "Greenland Dog","Hokkaido","Ibizan Hound","Icelandic Sheepdog","Italian Spitz",
    "Japanese Spitz","Kai","Keeshond","Kishu","Korea Jindo Dog","Laika (East Siberian)",
    "Laika (West Siberian)","Laika (Russian-European)","Norwegian Buhund",
    "Norwegian Elkhound (Black)","Norwegian Elkhound (Grey)","Norwegian Lundehund",
    "Peruvian Hairless Dog","Pharaoh Hound","Pomeranian","Samoyed","Shiba","Shikoku",
    "Siberian Husky","Swedish Lapphund","Swedish Vallhund","Thai Ridgeback",
    "Volpino Italiano","Xoloitzcuintle",
  ],
  6: [
    "Artois Hound","Basset Artésien Normand","Basset Bleu De Gascogne",
    "Basset Fauve De Bretagne","Basset Griffon Vendéen (Grand)","Basset Griffon Vendéen (Petit)",
    "Basset Hound","Bavarian Mountain Scent Hound","Beagle","Billy",
    "Black and Tan Coonhound","Bloodhound","Blue Gascony Basset","Bleu De Gascogne (Grand)",
    "Bleu De Gascogne (Petit)","Briquet Griffon Vendéen","Bruno Du Jura","Dalmatian",
    "Drever","Dunker","English Foxhound","Finnish Hound","Foxhound (American)",
    "Grand Anglo-Francais Blanc Et Noir","Grand Anglo-Francais Blanc Et Orange",
    "Grand Anglo-Francais Tricolore","Grand Griffon Vendéen","Haldenstövare",
    "Hamiltonstövare","Harrier","Hygenhund","Otterhound","Plott Hound",
    "Poitevin","Polish Hound","Porcelaine","Rhodesian Ridgeback","Schillerstövare",
    "Schweizer Laufhund","Schwarzwild Bracke","Slovenský Kopov","Smälandsstövare",
    "Steinbracke","Styrian Coarse-haired Hound","Tirolean Hound","Transylvanian Hound",
  ],
  7: [
    "Bracco Italiano","Braque D'Auvergne","Braque Du Bourbonnais","Braque Francais (Gascogne)",
    "Braque Francais (Pyrénées)","Braque Saint-Germain","Brittany","Burgos Pointer",
    "Czech Fousek","Drentse Patrijshond","English Setter","French Spaniel","German Longhaired Pointer",
    "German Shorthaired Pointer","German Wirehaired Pointer","Gordon Setter",
    "Hungarian Wirehaired Vizsla","Irish Red and White Setter","Irish Setter",
    "Istrian Coarse-Haired Hound","Italian Spinone","Korthals Griffon","Large Munsterlander",
    "Old Danish Pointer","Perdigueiro Portugues","Perdiguero De Burgos",
    "Picardy Spaniel","Pointer","Portuguese Pointer","Pudelpointer","Punta Griffon Korthals",
    "Setter Gordon","Slovakian Wirehaired Pointer","Small Munsterlander","Spanish Pointer",
    "Stabyhoun","Vizsla","Weimaraner","Wirehaired Pointing Griffon",
  ],
  8: [
    "American Cocker Spaniel","American Water Spaniel","Barbet","Boykin Spaniel",
    "Chesapeake Bay Retriever","Clumber Spaniel","Curly Coated Retriever","English Cocker Spaniel",
    "English Springer Spaniel","Field Spaniel","Flat Coated Retriever","French Water Dog",
    "German Spaniel","Golden Retriever","Irish Water Spaniel","Labrador Retriever",
    "Nederlandse Kooikerhondje","Nova Scotia Duck Tolling Retriever","Portuguese Water Dog",
    "Romagna Water Dog","Spanish Water Dog","Sussex Spaniel","Welsh Springer Spaniel",
    "Wetterhoun",
  ],
  9: [
    "Bichon Frisé","Bolognese","Boston Terrier","Brussels Griffon","Cavalier King Charles Spaniel",
    "Chihuahua (Long Coat)","Chihuahua (Smooth Coat)","Chinese Crested Dog",
    "Coton De Tuléar","Crested Dog","English Toy Terrier","French Bulldog",
    "Griffon Belge","Griffon Bruxellois","Havanese","Japanese Chin","Japanese Spitz",
    "King Charles Spaniel","Lhasa Apso","Löwchen","Maltese","Miniature Bull Terrier",
    "Miniature Pinscher","Papillon","Pekinese","Petit Brabançon","Poodle",
    "Poodle (Miniature)","Poodle (Standard)","Poodle (Toy)","Pug","Shih Tzu",
    "Silky Terrier","Tibetan Spaniel","Tibetan Terrier","Toy Fox Terrier","Yorkshire Terrier",
  ],
  10: [
    "Afghan Hound","Azawakh","Borzoi","Deerhound","Greyhound",
    "Hungarian Greyhound","Irish Wolfhound","Italian Greyhound","Magyar Agár",
    "Polish Greyhound","Saluki","Scottish Deerhound","Sloughi","Spanish Greyhound",
    "Whippet",
  ],
};
