export const SEED_JUDGES = [
  { id:"j1", slug:"margaret-thornton", name:"Margaret Thornton", country:"USA", flag:"🇺🇸", breeds:["Golden Retriever","Labrador Retriever","Flat-Coated Retriever"], group:"Sporting", licensed:1994, orgs:[{org:"AKC",id:"AKC-28841"},{org:"FCI",id:"FCI-00412"}], verified:true, claimedBy:"judge1@example.com", bio:"Forty years in Goldens. I've bred 23 champions and judged on five continents. I judge for correct movement and coat texture above all else. An honest critique is the best thing I can give you.", social:{instagram:"@margaret_thornton_goldens",facebook:"MargaretThorntonGoldens",linkedin:""}, photo:"MT" },
  { id:"j2", slug:"hans-werner-keller", name:"Hans-Werner Keller", country:"Germany", flag:"🇩🇪", breeds:["German Shepherd Dog","Rottweiler","Doberman Pinscher"], group:"Herding / Working", licensed:1988, orgs:[{org:"FCI",id:"FCI-00089"},{org:"KC",id:"KC-JG-1102"}], verified:true, claimedBy:"hw.keller@example.com", bio:"Former SV breed warden. I've judged the WUSV World Championship four times. What I look for: correct rear drive, solid nerves, and a head that screams the breed.", social:{instagram:"",facebook:"HWKellerJudge",linkedin:"hans-werner-keller"}, photo:"HK" },
  { id:"j3", slug:"siobhan-oreilly", name:"Siobhan O'Reilly", country:"Ireland", flag:"🇮🇪", breeds:["Irish Setter","Irish Water Spaniel","Kerry Blue Terrier"], group:"Sporting / Terrier", licensed:2001, orgs:[{org:"FCI",id:"FCI-01204"},{org:"KC",id:"KC-JG-2981"}], verified:false, claimedBy:null, bio:"", social:{}, photo:"SR" },
  { id:"j4", slug:"takeshi-yamamoto", name:"Takeshi Yamamoto", country:"Japan", flag:"🇯🇵", breeds:["Akita","Shiba Inu","Kishu Ken"], group:"Non-Sporting", licensed:1997, orgs:[{org:"JKC",id:"JKC-4421"},{org:"FCI",id:"FCI-00877"}], verified:false, claimedBy:null, bio:"", social:{}, photo:"TY" },
  { id:"j5", slug:"eleanor-blackwood", name:"Eleanor Blackwood", country:"UK", flag:"🇬🇧", breeds:["Border Collie","Rough Collie","Shetland Sheepdog"], group:"Herding", licensed:1991, orgs:[{org:"KC",id:"KC-JG-0044"},{org:"FCI",id:"FCI-00201"}], verified:true, claimedBy:"eblackwood@example.com", bio:"Collies have been my life since 1979. I judge for the working whole — a dog that can do the job its ancestors were bred to do. I award the dog that could still herd a flock at the end of the day.", social:{instagram:"@eleanor_blackwood_collies",facebook:"",linkedin:""}, photo:"EB" },
  { id:"j6", slug:"carlos-mendes", name:"Carlos Mendes", country:"Brazil", flag:"🇧🇷", breeds:["Fila Brasileiro","Dogo Argentino","Cimarron Uruguayo"], group:"Working", licensed:2005, orgs:[{org:"FCI",id:"FCI-02210"},{org:"CKC",id:"CKC-J-9982"}], verified:false, claimedBy:null, bio:"", social:{}, photo:"CM" },
  { id:"j7", slug:"patricia-van-houten", name:"Patricia Van Houten", country:"Netherlands", flag:"🇳🇱", breeds:["Dutch Shepherd","Keeshond","Samoyed"], group:"Herding / Working", licensed:1999, orgs:[{org:"FCI",id:"FCI-00654"}], verified:true, claimedBy:"patricia.vh@example.com", bio:"I've dedicated my career to the preservation of correct Dutch and Nordic type. My assignments have taken me from Tokyo to São Paulo. I write detailed critiques for every class winner.", social:{instagram:"@patriciavh_dogs",facebook:"",linkedin:"patricia-van-houten-judge"}, photo:"PV" },
  { id:"j8", slug:"robert-ashford", name:"Robert Ashford", country:"Australia", flag:"🇦🇺", breeds:["Australian Shepherd","Australian Cattle Dog","Kelpie"], group:"Herding", licensed:2003, orgs:[{org:"ANKC",id:"ANKC-J-3312"},{org:"FCI",id:"FCI-01899"}], verified:false, claimedBy:null, bio:"", social:{}, photo:"RA" },
];

export const SEED_REVIEWS = [
  { id:"r1", judgeId:"j1", userId:"u_s1", userName:"Sarah K.", breed:"Golden Retriever", show:"Westminster Invitational 2024", date:"2024-02-14", overall:5, breedKnowledge:5, consistency:4, ringManner:5, examinationThoroughness:5, punctuality:4, noviceFriendliness:5, handlerIndependence:4, critiqueQuality:5, wouldReturn:true, text:"Margaret is one of the best Golden judges on the circuit. She really understands correct movement and coat texture. Took her time with each dog, never felt rushed. My bitch went BOB and I felt it was completely deserved.", reply:null },
  { id:"r2", judgeId:"j1", userId:"u_s2", userName:"Tom B.", breed:"Labrador Retriever", show:"Crufts 2024", date:"2024-03-08", overall:4, breedKnowledge:5, consistency:3, ringManner:4, examinationThoroughness:4, punctuality:5, noviceFriendliness:4, handlerIndependence:3, critiqueQuality:4, wouldReturn:true, text:"Very knowledgeable on type, placed the correct dogs. A few placements in the class ring felt a bit inconsistent — the open bitch she put up first one class, then reversed with no clear reason. Still a solid judge.", reply:"Tom, thank you for the honest feedback. You're right that I reversed my open bitch placing — on second movement I saw a clear difference in rear extension that changed my mind. I should have been more consistent from the start." },
  { id:"r3", judgeId:"j2", userId:"u_s3", userName:"Lena W.", breed:"German Shepherd Dog", show:"Eurasia Show 2024", date:"2024-01-20", overall:5, breedKnowledge:5, consistency:5, ringManner:4, examinationThoroughness:5, punctuality:5, noviceFriendliness:3, handlerIndependence:5, critiqueQuality:5, wouldReturn:true, text:"Hans-Werner is the gold standard for GSD judging in Europe. His critiques were detailed and accurate. He rewarded correct angulation and did not fall for the overdone show dog look. Professional from start to finish.", reply:null },
  { id:"r4", judgeId:"j2", userId:"u_s4", userName:"Mike T.", breed:"Rottweiler", show:"German Sieger Show 2023", date:"2023-11-05", overall:3, breedKnowledge:4, consistency:2, ringManner:3, examinationThoroughness:3, punctuality:3, noviceFriendliness:2, handlerIndependence:2, critiqueQuality:3, wouldReturn:false, text:"Issues with consistency. Dogs he placed high in class were placed low in the group. I've shown under him twice and both times felt his final placements didn't match his initial selections.", reply:null },
  { id:"r5", judgeId:"j3", userId:"u_s5", userName:"Fiona M.", breed:"Irish Setter", show:"Clonmel Show 2024", date:"2024-06-02", overall:5, breedKnowledge:5, consistency:5, ringManner:5, examinationThoroughness:5, punctuality:5, noviceFriendliness:5, handlerIndependence:5, critiqueQuality:5, wouldReturn:true, text:"Siobhan is simply exceptional for the Irish breeds. She had my setter out and back twice, watched the whole class move together, and then made clean decisive placements. Written critiques are some of the best I've received.", reply:null },
  { id:"r6", judgeId:"j5", userId:"u_s6", userName:"Diana P.", breed:"Border Collie", show:"Scottish Kennel Club 2024", date:"2024-05-18", overall:5, breedKnowledge:5, consistency:5, ringManner:5, examinationThoroughness:5, punctuality:4, noviceFriendliness:5, handlerIndependence:5, critiqueQuality:5, wouldReturn:true, text:"Eleanor is a treat to show under. Genuine passion for herding dogs, and it shows. She rewarded working ability and correct structure. My youngster went Reserve and the critique was the most helpful feedback I've had all year.", reply:"Diana, thank you — this really means a lot. Your youngster was a standout in the class. Watch that left front — it's very minor but it will cost placements as she matures. A wonderful bitch." },
  { id:"r7", judgeId:"j7", userId:"u_s7", userName:"Anke V.", breed:"Keeshond", show:"Amsterdam Winner 2023", date:"2023-10-22", overall:5, breedKnowledge:5, consistency:5, ringManner:4, examinationThoroughness:5, punctuality:5, noviceFriendliness:4, handlerIndependence:5, critiqueQuality:5, wouldReturn:true, text:"Patricia is one of the most knowledgeable Dutch breed judges around. Thorough examination, clear in her reasoning. My Keeshond went BOB and she specifically called out his beautiful head and correct expression in the critique.", reply:null },
];
